FROM golang:1.10.0-alpine

RUN apk update && apk add git

RUN go get github.com/stretchr/testify/assert \
  github.com/gorilla/mux \
  github.com/satori/go.uuid

WORKDIR /go/src/github.com/srodrigo/payments
ADD . /go/src/github.com/srodrigo/payments

CMD go test -v ./...
